#!/bin/bash
# Script to copy landing page files from local Windows project to server
# Excludes signin, signup, and dashboard pages

echo "This script will help you copy landing page files from your local project."
echo ""
echo "Files to copy (landing/public pages only):"
echo "  - Home.tsx"
echo "  - About.tsx"
echo "  - Forex.tsx"
echo "  - Contact.tsx"
echo "  - Complaints.tsx"
echo "  - IntroducingBroker.tsx"
echo "  - DepositsWithdrawals.tsx"
echo "  - TradingContest.tsx"
echo "  - ButtonShowcase.tsx"
echo "  - WhatIsForex.tsx"
echo "  - ForexAdvantages.tsx"
echo "  - ForexPedia.tsx"
echo "  - DepositBonus.tsx"
echo "  - NoDepositBonus.tsx"
echo ""
echo "Files EXCLUDED (will not be copied):"
echo "  - SignIn.tsx"
echo "  - SignUp.tsx"
echo "  - dashboard/ folder"
echo "  - admin/ folder"
echo ""
echo "To copy files, use one of these methods:"
echo ""
echo "METHOD 1: Using SCP from your Windows machine (PowerShell):"
echo "  scp \"D:\\Project\\Mekness Project\\client\\src\\pages\\Home.tsx\" root@67.227.198.100:/root/mekness/client/src/pages/"
echo "  scp \"D:\\Project\\Mekness Project\\client\\src\\pages\\About.tsx\" root@67.227.198.100:/root/mekness/client/src/pages/"
echo "  (repeat for each file)"
echo ""
echo "METHOD 2: Using Git (recommended):"
echo "  1. On your local machine, commit only the landing page files"
echo "  2. Push to a branch"
echo "  3. On server, checkout only those specific files"
echo ""
echo "METHOD 3: Manual file-by-file copy using SFTP or file manager"
echo ""

