import PublicHeader from "@/components/PublicHeader";
import Footer from "@/components/Footer";
import AnimatedGrid from "@/components/AnimatedGrid";
import ParticleField from "@/components/ParticleField";
import { motion } from "framer-motion";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { 
  Users, TrendingUp, DollarSign, BarChart3, Globe, 
  Zap, Award, Shield, Headphones, Target, Check, 
  ArrowRight, Sparkles, TrendingDown
} from "lucide-react";
import { Link } from "wouter";

export default function IntroducingBroker() {
  const benefits = [
    {
      icon: DollarSign,
      title: "High Commission Structure",
      description: "Earn up to $15 per lot with our industry-leading rebate program. Competitive tiered structure that rewards volume and loyalty.",
      color: "cyber-cyan"
    },
    {
      icon: BarChart3,
      title: "Real-Time Tracking",
      description: "Advanced IB dashboard with live statistics, client activity monitoring, and detailed commission breakdowns updated every second.",
      color: "electric-purple"
    },
    {
      icon: Users,
      title: "Unlimited Referrals",
      description: "No cap on the number of clients you can refer. Build your network and scale your earnings exponentially.",
      color: "neon-green"
    },
    {
      icon: Sparkles,
      title: "Marketing Support",
      description: "Professional marketing materials, banners, landing pages, and multilingual content to boost your conversion rates.",
      color: "primary"
    },
    {
      icon: Headphones,
      title: "Dedicated IB Manager",
      description: "Personal account manager available 24/7 to support your growth, answer questions, and optimize your strategy.",
      color: "hot-pink"
    },
    {
      icon: Target,
      title: "Performance Bonuses",
      description: "Monthly and quarterly incentives for top performers. Extra rewards for reaching volume milestones and client retention.",
      color: "primary"
    },
  ];

  const commissionTiers = [
    {
      tier: "Starter",
      volume: "0-50 Lots/Month",
      commission: "$8 per lot",
      features: [
        "Basic IB Dashboard",
        "Email Support",
        "Standard Marketing Materials",
        "Monthly Payouts"
      ],
      popular: false
    },
    {
      tier: "Professional",
      volume: "51-200 Lots/Month",
      commission: "$12 per lot",
      features: [
        "Advanced IB Dashboard",
        "Priority Support",
        "Custom Marketing Materials",
        "Bi-Weekly Payouts",
        "Performance Analytics"
      ],
      popular: true
    },
    {
      tier: "Expert",
      volume: "201-500 Lots/Month",
      commission: "$14 per lot",
      features: [
        "Full-Feature Dashboard",
        "Dedicated IB Manager",
        "White-Label Solutions",
        "Weekly Payouts",
        "Advanced API Access",
        "Revenue Share Options"
      ],
      popular: false
    },
    {
      tier: "Master IB",
      volume: "500+ Lots/Month",
      commission: "$15+ per lot",
      features: [
        "Enterprise Dashboard",
        "24/7 VIP Support",
        "Full White-Label Platform",
        "Daily Payouts",
        "Custom Integration",
        "Negotiable Commission Rates",
        "Co-Branding Opportunities"
      ],
      popular: false
    },
  ];

  const steps = [
    {
      step: "1",
      title: "Register as IB",
      description: "Complete the simple online application form. Approval typically within 24 hours.",
      icon: Users
    },
    {
      step: "2",
      title: "Access IB Portal",
      description: "Get instant access to your personalized dashboard, tracking links, and marketing materials.",
      icon: BarChart3
    },
    {
      step: "3",
      title: "Refer Clients",
      description: "Share your unique referral link via your website, social media, or direct outreach.",
      icon: TrendingUp
    },
    {
      step: "4",
      title: "Earn Commissions",
      description: "Receive commissions for every trade your referred clients execute. Paid out automatically.",
      icon: DollarSign
    },
  ];

  const faqs = [
    {
      question: "What is an Introducing Broker (IB)?",
      answer: "An Introducing Broker is a partner who refers clients to Rozka Capitals in exchange for commission on the trading volume generated by those clients. IBs act as intermediaries, helping traders find a reliable broker while earning passive income."
    },
    {
      question: "How much can I earn as an IB?",
      answer: "Earnings depend on your client volume and activity. Our commission structure ranges from $8 to $15+ per lot. Active IBs with 100+ clients can earn $5,000-$50,000+ per month. There's no upper limit."
    },
    {
      question: "When do I receive my commissions?",
      answer: "Commission payouts are processed according to your tier: Monthly (Starter), Bi-Weekly (Professional), Weekly (Expert), or Daily (Master IB). All commissions are calculated in real-time and visible in your dashboard."
    },
    {
      question: "Do I need to be a trader to become an IB?",
      answer: "No trading experience is required. However, understanding forex markets helps you better assist your referred clients. We provide comprehensive training and educational resources for all IBs."
    },
    {
      question: "Is there a cost to join the IB program?",
      answer: "The Rozka Capitals IB program is completely free to join. There are no setup fees, monthly charges, or hidden costs. You simply register, get approved, and start referring clients immediately."
    },
    {
      question: "Can I track my clients and earnings?",
      answer: "Yes! Your IB dashboard provides real-time tracking of referred clients, their trading activity, commission earned, pending payments, and detailed analytics. Full transparency at all times."
    },
  ];

  return (
    <div className="min-h-screen bg-background">
      <PublicHeader />
      
      {/* Hero Section */}
      <div className="relative min-h-screen flex items-center overflow-hidden pt-28 md:pt-40 pb-14 md:pb-20">
        <AnimatedGrid variant="cyber" />
        <ParticleField count={80} className="opacity-40" />
        {/* Background Image */}
        <div className="absolute inset-0 w-full h-full">
          <div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1920&q=75&auto=format&fit=crop')] bg-cover bg-center opacity-30"></div>
          <div className="absolute inset-0 bg-gradient-to-t from-black via-black/70 to-transparent"></div>
        </div>
        
        <div className="absolute inset-0 bg-gradient-to-tr from-primary/10 via-transparent to-primary/10"></div>

        <div className="container mx-auto px-4 sm:px-6 md:px-8 lg:px-12 xl:px-16 max-w-7xl relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="max-w-4xl mx-auto text-center"
          >
            {/* Badge - Golden Ratio: 16px base */}
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              className="inline-block mb-[2.618rem]"
            >
              <div className="px-6 py-2 bg-primary/10 border border-primary/30 rounded-full backdrop-blur-sm neon-gold">
                <span className="text-sm font-semibold text-primary">Earn While You Refer • Unlimited Potential</span>
              </div>
            </motion.div>
            
            {/* Main Title - Golden Ratio: 16px * 1.618^3 = ~67px (closest: 4.25rem = 68px) */}
            <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl xl:text-[4.25rem] font-bold mb-6 sm:mb-8 md:mb-[4.236rem] leading-[1.2] tracking-tight px-4">
              Become an <span className="block mt-4 sm:mt-6 md:mt-6 text-gradient-animated text-glow-gold inline-block pb-2">Introducing Broker</span>
            </h1>
            
            {/* Description - Golden Ratio: 16px * 1.618^1 = ~26px (closest: 1.625rem = 26px) */}
            <motion.p
              className="text-base sm:text-lg md:text-xl lg:text-[1.625rem] text-muted-foreground leading-relaxed max-w-3xl mx-auto mb-6 sm:mb-8 md:mb-[2.618rem] px-4"
              style={{ lineHeight: '1.75rem' }}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.4 }}
            >
              Partner with Rozka Capitals and earn industry-leading commissions. Refer traders, build your network, and create a sustainable revenue stream with up to <span className="text-primary font-bold">$15 per lot</span>.
            </motion.p>
            <div className="flex flex-col sm:flex-row gap-6 justify-center">
              <Link href="/signup">
                <Button size="lg" className="neon-gold magnetic-hover shadow-[0_6px_20px_0_rgba(212,175,55,0.42)]">
                  Apply Now <ArrowRight className="ml-2 w-5 h-5" />
                </Button>
              </Link>
              <Link href="/contact">
                <Button variant="outline" size="lg" className="neon-border-animate">
                  Contact IB Team
                </Button>
              </Link>
            </div>
          </motion.div>
        </div>
      </div>

      {/* Benefits Section */}
      <div className="py-20 px-4 sm:px-6 md:px-8 lg:px-12 xl:px-16">
        <div className="container mx-auto max-w-7xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-4">
              Why Partner with <span className="text-gradient-gold inline-block pb-2">Rozka Capitals</span>
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Industry-leading benefits designed to maximize your earning potential and support your growth.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {benefits.map((benefit, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
              >
                <Card className="p-6 glass-morphism border-primary/20 card-hover-3d h-full group">
                  <div className="w-14 h-14 rounded-xl bg-primary/10 flex items-center justify-center mb-4 group-hover:animate-pulse-glow">
                    <benefit.icon className="w-7 h-7 text-primary" />
                  </div>
                  <h3 className="text-xl font-semibold mb-3 group-hover:text-gradient-gold transition-all duration-300">
                    {benefit.title}
                  </h3>
                  <p className="text-muted-foreground leading-relaxed">
                    {benefit.description}
                  </p>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </div>

      {/* Commission Tiers */}
      <div className="py-20 px-4 sm:px-6 md:px-8 lg:px-12 xl:px-16 bg-gradient-to-b from-transparent via-primary/5 to-transparent">
        <div className="container mx-auto max-w-7xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-4">
              Commission <span className="text-gradient-gold">Structure</span>
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Transparent tiered pricing that rewards performance. The more you grow, the more you earn.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {commissionTiers.map((tier, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                className="relative"
              >
                {tier.popular && (
                  <div className="absolute -top-4 left-1/2 -translate-x-1/2 z-10">
                    <div className="px-4 py-1 bg-primary rounded-full text-primary-foreground text-xs font-semibold animate-pulse-glow">
                      MOST POPULAR
                    </div>
                  </div>
                )}
                <Card className={`p-6 h-full glass-morphism-strong border-primary/20 card-hover-3d ${tier.popular ? 'neon-border-animate' : ''}`}>
                  <div className="text-center mb-6">
                    <h3 className="text-2xl font-bold text-gradient-gold mb-2">{tier.tier}</h3>
                    <div className="text-sm text-muted-foreground mb-4">{tier.volume}</div>
                    <div className="text-3xl font-bold text-primary text-glow-gold">{tier.commission}</div>
                  </div>
                  <ul className="space-y-3">
                    {tier.features.map((feature, idx) => (
                      <li key={idx} className="flex items-start gap-2 text-sm">
                        <Check className="w-4 h-4 text-neon-green flex-shrink-0 mt-0.5" />
                        <span className="text-muted-foreground">{feature}</span>
                      </li>
                    ))}
                  </ul>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </div>

      {/* How It Works */}
      <div className="py-20 px-4 sm:px-6 md:px-8 lg:px-12 xl:px-16">
        <div className="container mx-auto max-w-6xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-4">
              How It <span className="text-gradient-gold">Works</span>
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Four simple steps to start earning commissions as a Rozka Capitals Introducing Broker.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {steps.map((step, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                className="relative"
              >
                <Card className="p-6 glass-morphism border-primary/20 card-hover-3d h-full text-center">
                  <div className="w-16 h-16 rounded-full bg-primary text-primary-foreground text-3xl font-bold flex items-center justify-center mx-auto mb-4 animate-pulse-glow">
                    {step.step}
                  </div>
                  <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mx-auto mb-4">
                    <step.icon className="w-6 h-6 text-primary" />
                  </div>
                  <h3 className="text-lg font-semibold mb-3">{step.title}</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    {step.description}
                  </p>
                </Card>
                {index < steps.length - 1 && (
                  <div className="hidden lg:block absolute top-1/2 -right-3 z-10">
                    <ArrowRight className="w-6 h-6 text-primary" />
                  </div>
                )}
              </motion.div>
            ))}
          </div>
        </div>
      </div>

      {/* FAQs */}
      <div className="py-20 px-4 bg-gradient-to-b from-transparent via-primary/5 to-transparent">
        <div className="container mx-auto max-w-4xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-4">
              Frequently Asked <span className="text-gradient-gold inline-block pb-2">Questions</span>
            </h2>
          </motion.div>

          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <motion.details
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.05 }}
                className="glass-morphism-strong border border-primary/20 rounded-xl p-6 group"
              >
                <summary className="flex items-center justify-between cursor-pointer text-left font-semibold text-lg hover:text-primary transition-colors">
                  {faq.question}
                  <span className="text-primary ml-4 group-open:rotate-180 transition-transform flex-shrink-0">▼</span>
                </summary>
                <p className="mt-4 text-muted-foreground leading-relaxed">
                  {faq.answer}
                </p>
              </motion.details>
            ))}
          </div>
        </div>
      </div>

      {/* CTA Section */}
      <div className="py-20 px-4 sm:px-6 md:px-8 lg:px-12 xl:px-16">
        <div className="container mx-auto max-w-5xl">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <Card className="glass-morphism-strong border-primary/20 p-8 md:p-12 text-center relative overflow-hidden">
              <div className="absolute inset-0 bg-gradient-to-br from-primary/10 via-transparent to-primary/10"></div>
              <div className="relative z-10">
                <h2 className="text-3xl md:text-4xl font-bold mb-4">
                  Ready to Start <span className="text-gradient-gold inline-block pb-2">Earning</span>?
                </h2>
                <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
                  Join 2,500+ active IBs worldwide. Apply today and start building your commission stream with Rozka Capitals.
                </p>
                <div className="flex flex-col sm:flex-row gap-4 justify-center">
                  <Link href="/signup">
                    <Button size="lg" className="neon-gold magnetic-hover shadow-[0_6px_20px_0_rgba(212,175,55,0.42)]">
                      Become an IB Now
                    </Button>
                  </Link>
                  <Link href="/contact">
                    <Button variant="outline" size="lg">
                      Speak to IB Support
                    </Button>
                  </Link>
                </div>
                <p className="text-sm text-muted-foreground/60 mt-6">
                  Free to join • No setup fees • 24-hour approval
                </p>
              </div>
            </Card>
          </motion.div>
        </div>
      </div>

      <Footer />
    </div>
  );
}

