// Country to cities mapping
export const COUNTRY_CITIES: Record<string, string[]> = {
  "Afghanistan": ["Kabul", "Herat", "Mazar-i-Sharif", "Kandahar", "Jalalabad"],
  "Albania": ["Tirana", "Durrës", "Vlorë", "Shkodër", "Fier"],
  "Algeria": ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
  "Andorra": ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "Sant Julià de Lòria"],
  "Angola": ["Luanda", "Huambo", "Lobito", "Benguela", "Kuito"],
  "Antigua and Barbuda": ["St. John's", "All Saints", "Liberta", "Potter's Village"],
  "Argentina": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "Tucumán", "Mar del Plata", "Salta", "Santa Fe", "San Juan"],
  "Armenia": ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Abovyan"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Newcastle", "Canberra", "Sunshine Coast", "Wollongong"],
  "Austria": ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"],
  "Azerbaijan": ["Baku", "Ganja", "Sumqayit", "Mingachevir", "Lankaran"],
  "Bahamas": ["Nassau", "Freeport", "West End", "Coopers Town"],
  "Bahrain": ["Manama", "Riffa", "Muharraq", "Hamad Town", "A'ali"],
  "Bangladesh": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
  "Barbados": ["Bridgetown", "Speightstown", "Oistins", "Holetown"],
  "Belarus": ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno"],
  "Belgium": ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège"],
  "Belize": ["Belize City", "San Ignacio", "Orange Walk", "Dangriga", "Corozal"],
  "Benin": ["Cotonou", "Porto-Novo", "Parakou", "Djougou", "Abomey-Calavi"],
  "Bhutan": ["Thimphu", "Phuntsholing", "Punakha", "Gelephu"],
  "Bolivia": ["La Paz", "Santa Cruz", "Cochabamba", "Sucre", "Oruro"],
  "Bosnia and Herzegovina": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar"],
  "Botswana": ["Gaborone", "Francistown", "Molepolole", "Serowe", "Maun"],
  "Brazil": ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre"],
  "Brunei": ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong"],
  "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"],
  "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya", "Banfora"],
  "Burundi": ["Bujumbura", "Gitega", "Muyinga", "Ruyigi", "Ngozi"],
  "Cabo Verde": ["Praia", "Mindelo", "Santa Maria", "São Filipe"],
  "Cambodia": ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Kampong Cham"],
  "Cameroon": ["Douala", "Yaoundé", "Garoua", "Bafoussam", "Bamenda"],
  "Canada": ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Kitchener"],
  "Central African Republic": ["Bangui", "Bimbo", "Mbaïki", "Berbérati", "Kaga-Bandoro"],
  "Chad": ["N'Djamena", "Moundou", "Sarh", "Abéché", "Kelo"],
  "Chile": ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta"],
  "China": ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Hangzhou", "Wuhan", "Xi'an", "Nanjing", "Tianjin"],
  "Colombia": ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena"],
  "Comoros": ["Moroni", "Mutsamudu", "Fomboni", "Domoni"],
  "Congo": ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Owando"],
  "Costa Rica": ["San José", "Cartago", "Alajuela", "Heredia", "Puntarenas"],
  "Croatia": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar"],
  "Cuba": ["Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara"],
  "Cyprus": ["Nicosia", "Limassol", "Larnaca", "Famagusta", "Paphos"],
  "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec"],
  "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  "Djibouti": ["Djibouti City", "Ali Sabieh", "Tadjourah", "Obock"],
  "Dominica": ["Roseau", "Portsmouth", "Marigot", "Berekua"],
  "Dominican Republic": ["Santo Domingo", "Santiago", "La Romana", "San Pedro de Macorís", "San Cristóbal"],
  "Ecuador": ["Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Machala"],
  "Egypt": ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said"],
  "El Salvador": ["San Salvador", "Santa Ana", "San Miguel", "Mejicanos", "Soyapango"],
  "Equatorial Guinea": ["Malabo", "Bata", "Ebebiyín", "Aconibe"],
  "Eritrea": ["Asmara", "Keren", "Massawa", "Assab", "Mendefera"],
  "Estonia": ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve"],
  "Eswatini": ["Mbabane", "Manzini", "Big Bend", "Malkerns"],
  "Ethiopia": ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Awassa"],
  "Fiji": ["Suva", "Lautoka", "Nadi", "Labasa", "Ba"],
  "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu"],
  "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille"],
  "Gabon": ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda"],
  "Gambia": ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni"],
  "Georgia": ["Tbilisi", "Batumi", "Kutaisi", "Rustavi", "Gori"],
  "Germany": ["Berlin", "Munich", "Hamburg", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Dortmund", "Essen", "Leipzig"],
  "Ghana": ["Accra", "Kumasi", "Tamale", "Takoradi", "Ashaiman"],
  "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"],
  "Grenada": ["St. George's", "Gouyave", "Grenville", "Victoria"],
  "Guatemala": ["Guatemala City", "Mixco", "Villa Nueva", "Quetzaltenango", "Escuintla"],
  "Guinea": ["Conakry", "Nzérékoré", "Kindia", "Boké", "Kankan"],
  "Guinea-Bissau": ["Bissau", "Bafatá", "Gabú", "Bissorã"],
  "Guyana": ["Georgetown", "Linden", "New Amsterdam", "Corriverton"],
  "Haiti": ["Port-au-Prince", "Carrefour", "Delmas", "Pétion-Ville", "Port-de-Paix"],
  "Honduras": ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba", "El Progreso"],
  "Hungary": ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs"],
  "Iceland": ["Reykjavík", "Kópavogur", "Hafnarfjörður", "Akureyri", "Reykjanesbær"],
  "India": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Pune", "Jaipur", "Surat"],
  "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang", "Makassar", "Palembang", "Depok", "Tangerang", "Bekasi"],
  "Iran": ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz"],
  "Iraq": ["Baghdad", "Basra", "Mosul", "Erbil", "Najaf"],
  "Ireland": ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  "Israel": ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva"],
  "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania"],
  "Jamaica": ["Kingston", "Montego Bay", "Spanish Town", "Portmore", "May Pen"],
  "Japan": ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kawasaki", "Kyoto", "Saitama"],
  "Jordan": ["Amman", "Zarqa", "Irbid", "Russeifa", "Wadi al-Sir"],
  "Kazakhstan": ["Almaty", "Nur-Sultan", "Shymkent", "Karaganda", "Aktobe"],
  "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  "Kiribati": ["Tarawa", "Betio", "Bairiki"],
  "Kosovo": ["Pristina", "Prizren", "Mitrovica", "Peja", "Gjakova"],
  "Kuwait": ["Kuwait City", "Al Ahmadi", "Hawalli", "Al Farwaniyah", "Al Jahra"],
  "Kyrgyzstan": ["Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok"],
  "Laos": ["Vientiane", "Pakse", "Savannakhet", "Luang Prabang", "Phonsavan"],
  "Latvia": ["Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala"],
  "Lebanon": ["Beirut", "Tripoli", "Sidon", "Tyre", "Byblos"],
  "Lesotho": ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse", "Mohale's Hoek"],
  "Liberia": ["Monrovia", "Gbarnga", "Kakata", "Bensonville", "Harper"],
  "Libya": ["Tripoli", "Benghazi", "Misrata", "Tarhuna", "Khoms"],
  "Liechtenstein": ["Vaduz", "Schaan", "Triesen", "Balzers"],
  "Lithuania": ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys"],
  "Luxembourg": ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange"],
  "Madagascar": ["Antananarivo", "Toamasina", "Antsirabe", "Mahajanga", "Fianarantsoa"],
  "Malawi": ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu"],
  "Malaysia": ["Kuala Lumpur", "George Town", "Ipoh", "Shah Alam", "Petaling Jaya", "Subang Jaya", "Johor Bahru", "Malacca City", "Kota Kinabalu", "Kuching"],
  "Maldives": ["Malé", "Addu City", "Fuvahmulah", "Kulhudhuffushi"],
  "Mali": ["Bamako", "Sikasso", "Mopti", "Koutiala", "Kayes"],
  "Malta": ["Valletta", "Birkirkara", "Mosta", "Qormi", "Żabbar"],
  "Marshall Islands": ["Majuro", "Ebeye", "Jaluit"],
  "Mauritania": ["Nouakchott", "Nouadhibou", "Rosso", "Kaédi", "Zouérat"],
  "Mauritius": ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes"],
  "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Juárez", "Torreón", "Querétaro", "San Luis Potosí"],
  "Micronesia": ["Palikir", "Weno", "Colonia"],
  "Moldova": ["Chișinău", "Tiraspol", "Bălți", "Bender", "Rîbnița"],
  "Monaco": ["Monaco", "Monte Carlo", "La Condamine"],
  "Mongolia": ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan", "Mörön"],
  "Montenegro": ["Podgorica", "Nikšić", "Pljevlja", "Bijelo Polje", "Cetinje"],
  "Morocco": ["Casablanca", "Rabat", "Fes", "Marrakech", "Tangier"],
  "Mozambique": ["Maputo", "Matola", "Beira", "Nampula", "Chimoio"],
  "Myanmar": ["Yangon", "Mandalay", "Naypyidaw", "Mawlamyine", "Bago"],
  "Namibia": ["Windhoek", "Rundu", "Walvis Bay", "Oshakati", "Swakopmund"],
  "Nauru": ["Yaren", "Denigomodu", "Aiwo"],
  "Nepal": ["Kathmandu", "Pokhara", "Patan", "Biratnagar", "Birgunj"],
  "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga"],
  "Nicaragua": ["Managua", "León", "Masaya", "Matagalpa", "Chinandega"],
  "Niger": ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua"],
  "Nigeria": ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt"],
  "North Korea": ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Sinuiju"],
  "North Macedonia": ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo"],
  "Norway": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Bærum"],
  "Oman": ["Muscat", "Seeb", "Salalah", "Bawshar", "Sohar"],
  "Pakistan": ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Multan"],
  "Palau": ["Ngerulmud", "Koror", "Melekeok"],
  "Palestine": ["Gaza", "Hebron", "Nablus", "Jericho", "Ramallah"],
  "Panama": ["Panama City", "San Miguelito", "Tocumen", "David", "Arraiján"],
  "Papua New Guinea": ["Port Moresby", "Lae", "Arawa", "Mount Hagen", "Popondetta"],
  "Paraguay": ["Asunción", "Ciudad del Este", "San Lorenzo", "Luque", "Capiatá"],
  "Peru": ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura"],
  "Philippines": ["Manila", "Quezon City", "Caloocan", "Davao City", "Cebu City", "Zamboanga City", "Antipolo", "Cagayan de Oro", "Pasig", "Valenzuela"],
  "Poland": ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań"],
  "Portugal": ["Lisbon", "Porto", "Amadora", "Braga", "Setúbal"],
  "Qatar": ["Doha", "Al Rayyan", "Umm Salal", "Al Wakrah", "Al Khor"],
  "Romania": ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța"],
  "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan"],
  "Rwanda": ["Kigali", "Butare", "Gitarama", "Ruhengeri", "Gisenyi"],
  "Saint Kitts and Nevis": ["Basseterre", "Charlestown", "Sandy Point Town"],
  "Saint Lucia": ["Castries", "Gros Islet", "Vieux Fort", "Soufrière"],
  "Seychelles": ["Victoria", "Anse Boileau", "Beau Vallon"],
  "Sierra Leone": ["Freetown", "Bo", "Kenema", "Makeni", "Koidu"],
  "Singapore": ["Singapore"],
  "Slovakia": ["Bratislava", "Košice", "Prešov", "Žilina", "Banská Bystrica"],
  "Slovenia": ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje"],
  "Solomon Islands": ["Honiara", "Auki", "Gizo"],
  "Somalia": ["Mogadishu", "Hargeisa", "Kismayo", "Bosaso", "Berbera"],
  "South Africa": ["Cape Town", "Johannesburg", "Durban", "Pretoria", "Port Elizabeth"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
  "South Sudan": ["Juba", "Wau", "Malakal", "Yambio", "Rumbek"],
  "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza"],
  "Sri Lanka": ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo"],
  "Sudan": ["Khartoum", "Omdurman", "Port Sudan", "Kassala", "El Geneina"],
  "Suriname": ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Meerzorg"],
  "Sweden": ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås"],
  "Switzerland": ["Zürich", "Geneva", "Basel", "Bern", "Lausanne"],
  "Syria": ["Damascus", "Aleppo", "Homs", "Latakia", "Hama"],
  "Taiwan": ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Hsinchu"],
  "Tajikistan": ["Dushanbe", "Khujand", "Kulob", "Qurghonteppa", "Istaravshan"],
  "Tanzania": ["Dar es Salaam", "Mwanza", "Arusha", "Dodoma", "Mbeya"],
  "Thailand": ["Bangkok", "Nonthaburi", "Nakhon Ratchasima", "Chiang Mai", "Hat Yai"],
  "Timor-Leste": ["Dili", "Baucau", "Maliana", "Liquiçá"],
  "Togo": ["Lomé", "Sokodé", "Kara", "Atakpamé", "Kpalimé"],
  "Tonga": ["Nuku'alofa", "Neiafu", "Haveluloto"],
  "Trinidad and Tobago": ["Port of Spain", "San Fernando", "Chaguanas", "Arima", "Couva"],
  "Tunisia": ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte"],
  "Turkey": ["Istanbul", "Ankara", "İzmir", "Bursa", "Antalya"],
  "Turkmenistan": ["Ashgabat", "Türkmenabat", "Daşoguz", "Mary", "Balkanabat"],
  "Tuvalu": ["Funafuti", "Vaiaku"],
  "Uganda": ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja"],
  "Ukraine": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman"],
  "United Kingdom": ["London", "Birmingham", "Manchester", "Glasgow", "Liverpool", "Leeds", "Sheffield", "Edinburgh", "Bristol", "Cardiff"],
  "United States": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose"],
  "Uruguay": ["Montevideo", "Salto", "Ciudad de la Costa", "Paysandú", "Las Piedras"],
  "Uzbekistan": ["Tashkent", "Samarkand", "Namangan", "Andijan", "Bukhara"],
  "Vanuatu": ["Port Vila", "Luganville", "Norsup"],
  "Vatican City": ["Vatican City"],
  "Venezuela": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay"],
  "Vietnam": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Haiphong", "Can Tho"],
  "Yemen": ["Sana'a", "Aden", "Ta'izz", "Al Hudaydah", "Ibb"],
  "Zambia": ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola"],
  "Zimbabwe": ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru"],
};

export function getCitiesForCountry(country: string): string[] {
  return COUNTRY_CITIES[country] || [];
}

